### ISSUE TITLE
Post Milestone 2 Refactor

### ISSUE THREAD

**Issue by nasser** [nasser/magic#124]
The codebase is in a little bit of a mess following the previous milestone and the type-emission tech that was developed for it. Before getting too far we should clean things up.

- [x] Share code between `proxy`, `reify`, `deftype` analysis and type generation
- [x] Share code between `proxy`, `reify`, `deftype` compilers
- [x] Move typed analysis passes into own namespace
- [x] Move `magic.core/*modules*` into own namespace visible to both `magic.core` and `magic.analyzer.types`
